function [ output_args ] = proprioceptivedrift( input_args )
%PROPRIOCEPTIVEDRIFT 
% Takes the .cvs file generated by Unity and creates the linear graphs of
% the hand position compared to the proprioceptive drift measure. 
%   




end

